// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqtYFpLrPwfll0x27jIfoNhFzZcIywYkg',
    appId: '1:894254272808:web:0cdec3f3440c084e94001d',
    messagingSenderId: '894254272808',
    projectId: 'testingfirebase-65f36',
    authDomain: 'testingfirebase-65f36.firebaseapp.com',
    storageBucket: 'testingfirebase-65f36.appspot.com',
    measurementId: 'G-M0NB9HLNSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnqXgKAIAcIRjN2Y5dlIgWDnjGaVuRgJk',
    appId: '1:894254272808:android:721f2550a94ff66794001d',
    messagingSenderId: '894254272808',
    projectId: 'testingfirebase-65f36',
    storageBucket: 'testingfirebase-65f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wT2UAtahhtfkCypWpDL8lu_xzcyJdug',
    appId: '1:894254272808:ios:417c15f5e7ee28a294001d',
    messagingSenderId: '894254272808',
    projectId: 'testingfirebase-65f36',
    storageBucket: 'testingfirebase-65f36.appspot.com',
    iosBundleId: 'com.example.testingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5wT2UAtahhtfkCypWpDL8lu_xzcyJdug',
    appId: '1:894254272808:ios:417c15f5e7ee28a294001d',
    messagingSenderId: '894254272808',
    projectId: 'testingfirebase-65f36',
    storageBucket: 'testingfirebase-65f36.appspot.com',
    iosBundleId: 'com.example.testingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqtYFpLrPwfll0x27jIfoNhFzZcIywYkg',
    appId: '1:894254272808:web:c758be789713380494001d',
    messagingSenderId: '894254272808',
    projectId: 'testingfirebase-65f36',
    authDomain: 'testingfirebase-65f36.firebaseapp.com',
    storageBucket: 'testingfirebase-65f36.appspot.com',
    measurementId: 'G-RXMZ4DDZ4Y',
  );
}
